### ISSUE TITLE
faction.vehicles.find

### ISSUE THREAD

**Issue by florian133** [Stuyk/altv-athena#118]
After restarting the server failure on vehicle check for already spawned faction vehicles

branch 3.0.4

[21:36:57][Error] [V8] Exception at core:file:///C:/Users/Server/altv-athena-private/altv-private/resources/core/server-plugins/core-factions/src/funcs.js:68
[21:36:57][Error]           const index = faction.vehicles.findIndex((fv)=>fv.id === vehicle.data._i...
[21:36:57][Error]   TypeError: Cannot read property 'findIndex' of undefined
    at handleFactionVehicleChecks (file:///C:/Users/Server/altv-athena-private/altv-private/resources/core/server-plugins/core-factions/src/funcs.js:68:40)
    at Function.check (file:///C:/Users/Server/altv-athena-private/altv-private/resources/core/server/systems/rules.js:22:28)
    at toggleLock (file:///C:/Users/Server/altv-athena-private/altv-private/resources/core/server/systems/vehicle.js:355:26)

**Comment by Booster1212** [comment]
Factions are being reworked atm. So i highly doubt its an actual matter.

I doubt the new faction system is finished also.

**Comment by florian133** [comment]
was just to give an headsup about an issue.

#closed
