### ISSUE TITLE
Reentering the game after setting the player's uniform cannot access the character-select plugin

### ISSUE THREAD

**Issue by MrKangM** [Stuyk/altv-athena#422]
After setting the player uniform, even if the player uniform is removed before offline, the character information cannot be read after the next login.

**error message**
`[Error] Uncaught exception: TypeError: Cannot read properties of null (reading 'length')
    at Module.update (file:///D:/altProject/alt-V-Project/resources/core/server/systems/inventory/clothing.js:252:37)
    at showCharacter (file:///D:/altProject/alt-V-Project/resources/core/plugins/character-select/server/index.js:54:39)
    at Object.show [as callback] (file:///D:/altProject/alt-V-Project/resources/core/plugins/character-select/server/index.js:35:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by Stuyk** [comment]
Fixed in `5.1.0`
